### ISSUE TITLE
Project does not build

### ISSUE THREAD

**Issue by ThorMalleuson** [Jinten/NodeGraph#1]
MainWindow.xaml(160,14): error MC3074: The tag 'Interaction.Triggers' does not exist in XML namespace 'http://schemas.microsoft.com/expression/2010/interactivity'. Line 160 Position 14.

Using Visual Studio version 16.9.4

**Comment by Jinten** [comment]
I'm sorry for the late response.  
You need to install "Microsoft.Xaml.Behaviors.Wpf" package using Nuget in VS2019.  
Because System.Windows.Interactivity was deleted from VS2019.  
Or you can resolve that install Blend for Visual Studio SDK for .NET with Visual Studio Installer.

**Comment by Jinten** [comment]
Fixed for using "Microsoft.Xaml.Behaviors.Wpf" in sample project.
23480c6314a1befc163e85d6f3cc9432b434b81d

You can build with VisualStudio2019.
