### ISSUE TITLE
Unable to click output to drag out nodelink

### ISSUE THREAD

**Issue by lingme** [Jinten/NodeGraph#2]
Hi, I admire your technique, it's a great project

But when I run this project, I can't drag and drop a nodelink through the output like the Readme document. Clicking the output and dragging can only move the node.

thank you, Have a nice day

**Comment by Jinten** [comment]
I'm sorry for replying late.
I'll check own behavior again.
And would you able to tell me your environment?
I want to ask that you are using visual studio version, windows os version. Thanks for reporting.

**Comment by lingme** [comment]
Thank you so much for your reply, I am very excited.
I have fixed this, but forgot to submit pull requests, sorry.
I found that the problem is in **Node_MouseDown** function of **NodeGraph** , when sender is not **GroupNode** but **NodeConnectorContent** type, **NodeConnectorContent** object must be obtained from **OriginalSource** instead of sender object.


This is my fix code:
```csharp
void Node_MouseDown(object sender, MouseButtonEventArgs e) 
{
  _PressedRightBotton = e.RightButton == MouseButtonState.Pressed;
  if (sender is GroupNode groupNode) 
  {
    groupNode.CaptureToResizeDragging();
    if (groupNode.IsDraggingToResize) {
      _DraggingToResizeGroupNode = groupNode;
      e.Handled = true;

      return;
    }
  }

  //fix code
  var originalSender = e.OriginalSource as FrameworkElement;
  if (originalSender is FrameworkElement fwElement && fwElement.Tag is NodeConnectorContent connector) 
  {
    // clicked on the connector
    var posOnCanvas = connector.GetContentPosition(Canvas);

    var nodeLink = new NodeLink(Canvas, posOnCanvas.X, posOnCanvas.Y, Scale, connector) 
    {
        DataContext = null,
        Style = NodeLinkStyle ?? NodeLinkAnimationStyle
    };

       _DraggingNodeLinkParam = new DraggingNodeLinkParam(nodeLink, connector);
       Canvas.Children.Add(_DraggingNodeLinkParam.NodeLink);

       Cursor = Cursors.Cross;
    } 
    else if (IsOffsetMoveWithMouse(e) == false) 
    {
       // clicked on the Node
       StartToMoveDraggingNode(e.GetPosition(Canvas), (NodeBase) e.Source);
     }
     e.Handled = true;
}
```

**Comment by Jinten** [comment]
Thank you for submitting detail the code.
I made a mistake fixing detecting process. I fixed the bug and refactored some code.
Please check the 24a9659ac7d3b50b5d64bf5221d89dbf35639c23 ([line](https://github.com/Jinten/NodeGraph/commit/24a9659ac7d3b50b5d64bf5221d89dbf35639c23#diff-dd871d54b21ef91adb3ea278f4bb5fcd643c1d97238e63fa3dc86941384be349R1144)) commit. Thank you.

**Comment by lingme** [comment]
Thank you so much, you are one of the best WPF developers I have ever met, have a nice day
