### ISSUE TITLE
.net 6

### ISSUE THREAD

**Issue by AndreasGeorg** [Jinten/NodeGraph#3]
I have tried to compile the project with .net6, it compiles but when I start the application no window is opened. Is there any plan to port the project to .net6?

**Comment by Jinten** [comment]
I'm sorry for replying late.
Supporting .NET6 is noted Roadmap, but I supported .NET6, please check https://github.com/Jinten/NodeGraph/commit/91084726d5dede4df250741dc298f7f12dfb6761.

You can launch PreviewTest csproj as .NET6.
The project depends NodeGraph library made by .NET6.

If you check the project and no problem for behavior, please close this issue. :)

**Comment by AndreasGeorg** [comment]
Thank you, for your work
